---
title: "The Relationship Between Life Expectancy and the Gini Coefficient"
author:
  - "Vishwamber Reddy"
  - "Cayou Shao"
  - "Hongyu Yin"
toc: true
format: html
---

# **Executive summary**

Studying the relationship between life expectancy and the Gini coefficient is essentially exploring the connection between economic inequality and health inequality.

In this era that emphasizes economic development, people's physical health should be equally prioritized.

By comparing the Gini coefficients and life expectancies across different economies and regions, we can gain a more intuitive and comprehensive understanding of a particular economy or region's development level.

Furthermore, researching the relationship between these inequalities can provide new directions for economic development goals.

# **Introduction**

## **Research Question**

In this study, we will explore whether reducing economic inequality contributes to mitigating disparities in life expectancy.

The Gini coefficient is a key indicator for measuring economic inequality within a country or region.Therefore, by examining the relationship between the Gini coefficient and life expectancy, we aim to assess the importance of balanced economic development.

## **Dataset introduction**

We utilize **life expectancy** data from **Our World** in Data and **Gini coefficient** data from **the World Bank**, spanning 1990 to 2020 and covering multiple countries and regions.

-   The body of the report should contain the following sections:

    **Methodology**: How we processed the data.

    **Results**: What conclusions we reached.

    **Discussion, conclusion and recommendations**: Our Intended Message.

# **Methodology**

Maximum 300 words

Should include a figure and a table and those must be referenced in the text and have adequate captions

# **Results**

Maximum 200 words. Should include either a figure or a table.

# **Discussion, conclusion and recommendations**

# **Reference section**

Include at least 1 reference.
